FROM mongo:6.0

COPY docker-entrypoint-initdb.d/init-mongo.js /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.js && \
    echo '#!/bin/bash\nmongosh afisha --eval "load('\''/docker-entrypoint-initdb.d/init-mongo.js'\'')"' > /always-init.sh && \
    chmod +x /always-init.sh

CMD ["/always-init.sh"]